### ISSUE TITLE
Duration animation not working

### ISSUE THREAD

**Issue by AJFiori** [netfox01/notiModal#2]
Love the modal and was easily customizable, but I am having issues with setting the duration to where I want it to show for only 5000 and then disappear.  I currently have it set to this:
duration: '500ms',
Which states in the functions guide.

any ideas?

**Comment by eissasoubhi** [comment]
Hi @AJFiori , the duration option is for the time the modal will take to be completely visible (with animation). the feature you are looking for is the **auto-hide after a period of time**.
I added two options to the plugin to meet your requirement: '**auto_hide**' and '**show_duration**', see the doc for more info.

NB: I changed the name of the option duration to animation_duration.

**Comment by AJFiori** [comment]
That worked thank you. I was using the JS function "animate" when grabbing the ID, but I will use your setting options. Thanks again!

**Comment by AJFiori** [comment]
If I wrap your plugin in a setInterval function will it work and display based on the interval time? So far its not seeing to work

**Comment by eissasoubhi** [comment]
you don't have to use setInterval, i just added **onClose** event that you can use that way :

```javascript
    $.notiModal.init("my_modal", {
        // ....
        auto_hide: true,
        show_duration:3000,
        onClose: function ($noti_modal) {
            $noti_modal.show({
               // delay the modal before showing it again
                'delay': 3000
            });
        }
    })
```

this will keep showing the modal every 3s (show_duration).

**Comment by AJFiori** [comment]
Quick question. If I wanted to iterate through an array of strings and everytime the modal displays the text would be different each time. (whatever is coming from the array). Is there a specific way I need to do this since its a plugin? I tried putting the modal inside a for loop and would get an error saying that modal was already created, so I incremented the ID and still wasn't liking it.

**Comment by eissasoubhi** [comment]
You can use the show method to override the content option while iterating through the strings array 

```javascript
var messages = ['hello there!', 'follow me!', 'give me a star!', 'fork me on github!', 'thank you!'];

if (messages.length) {
    var i = 0;
    $.notiModal.init("my_modal", {
        // ....
        auto_hide: true,
        show_duration:3000,
        onClose: function ($noti_modal) {
            $noti_modal.show({
                i++;
                if (messages[i]) {
                    $noti_modal.show({
                        'delay': 1000,
                        'content': messages[i],
                    });
                }
            });
        }
    }).show();
}
```

**Comment by AJFiori** [comment]
I followed your guidelines and updated my js files, but this is what I'm getting in my function when I try and do the same. I marked where its erroring. 

function GetStatusBoardNotification() {
    var hidLogin = $('[id*=hidLogin]').val();
    var hidCurrent = $('[id*=hidCurrentlyHave]').val();
    var hidWait = $('[id*=hidWaitingFor]').val();
    var hidHello = $('[id*=hidHello]').val();
    var hidOk = $('[id*=hidOk]').val();
    var tacos = ["Taco 1", "Taco 2", "Taco 3", "Taco 4", "Taco 5", "Taco 6"];

    if(tacos.length){
        var i =0;
        $.notiModal.init("second_modal", {        
                title:"<span class='icon-warning'></span>" + " " + " <strong style='padding-left:100px;font-size:23px;'>"+ hidHello + " " + hidLogin +"!</strong>",
                top: 300,
                ok: hidOk,
                //close:hidClose,
                max_width: 800,
                animation_duration: '500ms',
                auto_hide:true,
                show_duration: 5000,
                sound: false,
                //content: hidCurrent + "  " + "<strong>" + text + "</strong> " + hidWait,
                // ok callback
                onOkClick: function ($noti_modal) {
                    $noti_modal.show({
                      i++;//Red squig
                        if(tacos[i]){
                            $noti_modal.show({
                                'delay': 1000,
                                'content': tacos[i],
                            });
                    
                        }
                   });//Red squig
                }
            }).show();//Red squig
           
           setInterval(function(){ $.notiModal.get("second_modal").show({force:true}); },5000);
    } //Red squig
}

All my closing tags are correct

**Comment by AJFiori** [comment]
I got it to display the new text but in the cosole.log. For some reason my show isn't working when I click on the OKClick:

var tacos = ["Taco 1", "Taco 2", "Taco 3", "Taco 4", "Taco 5", "Taco 6"];
    if(tacos.length) {
        var i = 0;
        // Create notiModal
        $.notiModal.init("second_modal", {        
            title:"<span class='icon-warning'></span>" + " " + " <strong style='padding-left:100px;font-size:23px;'>" + hidHello + " " + hidLogin +"!</strong>",
            top: 300,
            ok: hidOk,
            //close:hidClose,
            max_width: 800,
            animation_duration: '500ms',
            auto_hide: true,
            show_duration: 5000,
            sound: false,
            content: hidCurrent + "  " + "<strong>" + tacos[i] + "</strong> " + hidWait,
            // ok callback
            onOkClick: function (noti_modal) {
                i++;
                if(tacos[i]){
                    console.log("onOKClick IF: " + tacos[i])
                    noti_modal.show({
                        content: tacos[i]
                });
               }
            },
        }).show({force:true});
   }

**Comment by eissasoubhi** [comment]
I'm sorry, in my example code, I made a mistake, the part inside onClose should be like this:
```javascript
onClose: function ($noti_modal) {
    i++;
    if (messages[i]) {
        $noti_modal.show({
            'delay': 1000,
            'content': messages[i],
        });
    }
}
```

**Comment by AJFiori** [comment]
That's what I currently have:
var tacos = ["Taco 1", "Taco 2", "Taco 3", "Taco 4", "Taco 5", "Taco 6"];
    if(tacos.length) {
        var i = 0;
        // Create notiModal
        $.notiModal.init("second_modal", {        
            title:"<span class='icon-warning'></span>" + " " + " <strong style='padding-left:100px;font-size:23px;'>" + hidHello + " " + hidLogin +"!</strong>",
            top: 300,
            ok: hidOk,
            //close:hidClose,
            max_width: 800,
            animation_duration: '500ms',
            auto_hide: true,
            show_duration: 5000,
            sound: false,
            content: hidCurrent + "  " + "<strong>" + tacos[i] + "</strong> " + hidWait,
            // ok callback
            onOkClick: function ($noti_modal) {
                i++;
                if (tacos[i]) {
                    alert(tacos[i]);
                    $noti_modal.show({
                        'delay': 1000,
                        'content': tacos[i]
                    });
                }
            }
        }).show({force:true});
   }
    setInterval(function(){$.notiModal.get("second_modal").show({force:true});},hidTimer);

When I click the ok button I get my alert to display "Taco 2", I hit okay and when the notification comes again it still at "Taco 1"

**Comment by eissasoubhi** [comment]
I added some changes to the plugin, download the new version and use the code below, I tested it and it works.:
```javascript
var hidHello = 'hello',
    hidLogin = 'eissa',
    hidCurrent = 'this is',
    hidWait = 'wait',
    hidTimer = 1000,
    hidOk = 'ok';
var tacos = ["Taco 1", "Taco 2", "Taco 3", "Taco 4", "Taco 5", "Taco 6"];
if (tacos.length) {
    var i = 0;
    // Create notiModal
    $.notiModal.init("second_modal", {
        title: "" + " " + " " + hidHello + " " + hidLogin + "!",
        top: 300,
        ok: hidOk,
        //close:hidClose,
        max_width: 800,
        animation_duration: '500ms',
        auto_hide: true,
        show_duration: 5000,
        sound: false,
        content: hidCurrent + " " + "" + tacos[i] + " " + hidWait,
        // ok callback
        onOkClick: function($noti_modal) {
            i++;
            if (tacos[i]) {
                // alert(tacos[i]);
                $noti_modal.hide(function(nmodal) {
                    // show the modal again after the one before is completly hidden 
                    $noti_modal.show({
                        'delay': 1000,
                        'content': tacos[i]
                    });
                });
            }
        }
    }).show({
        force: true
    });
}
```
